caraml-dev/xp

ui/src/experiments/components/form/CreateExperimentForm.js, ui/src/experiments/components/form/EditExperimentForm.js, ui/src/experiments/components/form/validation/schema.js, ui/src/services/experiment/Segment.js, ui/src/services/segmenter/Segmenter.js, ui/src/settings/segmenters/components/form/components/SegmenterGeneralPanel.js
This PR includes small UI fixes.
1. When the experiment data is posted from Create / Edit forms, a recent change (in https://github.com/gojek/turing-experiments/pull/16) was added to parse each segmenter value from string to the registered type. But this is unnecessary as the values in the options list are already of the correct type. The only occasion when it must be parsed from string is when it's keyed into a free-form text area, which happens if there are no pre-defined options for the segmenter (such as with S2ID) - that is handled [here](https://github.com/gojek/turing-experiments/blob/main/ui/src/experiments/components/form/components/segment_config/SegmenterConfigRow.js#L52). Hence, the parsing onSubmit experiment has now been removed in …
=> Custom Segmenters: Miscellaneous UI Bugfixes

management-service/services/segmenter_service.go, ui/src/experiments/components/form/CreateExperimentForm.js, ui/src/experiments/components/form/EditExperimentForm.js, ui/src/experiments/components/form/validation/schema.js, ui/src/segments/components/form/CreateSegmentForm.js, ui/src/segments/components/form/EditSegmentForm.js, ui/src/segments/components/form/validation/schema.js, ui/src/services/experiment/Segment.js, ui/src/services/segmenter/SegmenterScope.js, ui/src/services/segmenter/SegmenterStatus.js, ui/src/settings/components/form/components/segmenter_section/SegmenterCard.js, ui/src/settings/segmenters/details/SegmenterDetailsView.js
This PR fixes a handful of small UI bugs.
1. When a segmenter is removed from the Project Settings, and a previously created inactive experiment that uses it is edited, the validation fails. This is addressed in [this change](https://github.com/gojek/turing-experiments/pull/19/files#r923033010).
2. When a 'required' custom segmenter does not have any values in the segment config, the UI would still allow it. This is addressed by [this change](https://github.com/gojek/turing-experiments/pull/19/files#r923035740).
3. Standalone segments were not checking segmenter types. This has been added.
Other than this, some miscellaneous refactoring has been done.
=> Miscellaneous UI bugfixes and refactoring

management-service/models/custom_segmenter.go, management-service/models/custom_segmenter_test.go, management-service/models/experiment_segment.go, management-service/services/segmenter_service.go
This PR introduces a bug fix that occurs when filtering experiments using segmenter values - when using segmenter values that are of the type real (`float` in go), experiments that have these values specified do not get filtered and displayed correctly in the `ListExperimentView`. 
E.g. Searching for experiments with the segmenter value corresponding to 1.4 (`o4`) for `custom_float` does not return the experiment named 'test':
**Details**
The bug is caused by the backend storing float values as strings with trailing zeroes e.g. "1.40000", leading the gorm string condition search queries to fail when given search parameters without them i.e. "1.4". 
The simple fix proposed in this PR thus enforces the strings generated from float values to have no …
=> [BUG] Fix experiment search filters when using real segmenter values

.github/actions/setup-tests/action.yml, .github/workflows/plugins.yml, .github/workflows/xp.yml, Makefile, clients/go.mod, common/go.mod, management-service/go.mod, management-service/go.sum, management-service/services/experiment_history_service_test.go, management-service/services/experiment_service_test.go, management-service/services/project_settings_service_test.go, management-service/services/pubsub_publisher_service_test.go, management-service/services/segment_history_service_test.go, management-service/services/segment_service_test.go, management-service/services/treatment_history_service_test.go, plugins/turing/Dockerfile, plugins/turing/go.mod, plugins/turing/go.sum, treatment-service/go.mod, treatment-service/go.sum
This PR is to keep our Go version up-to-date, by upgrading from `1.16` to  `1.18`.
`NONE`
=> Update Go versions in all modules

.pre-commit-config.yaml, CONTRIBUTING.md, Makefile, README.md, infra/charts/management-service/Chart.yaml, infra/charts/management-service/README.md, infra/charts/management-service/templates/service-swagger.yaml, infra/charts/management-service/templates/service-xp.yaml, infra/charts/treatment-service/Chart.yaml, infra/charts/treatment-service/README.md, infra/charts/treatment-service/templates/service-swagger.yaml, infra/charts/treatment-service/templates/service-xp.yaml
Istio [requires](https://istio.io/v1.0/docs/setup/kubernetes/spec-requirements/) service ports to be named in order to work correctly with the routing features. (It is also explained here in detail: [Protocol Selection](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/)). While the current chart works correctly with some basic usage of Istio (i.e. exposing a service via VirtualService), it fails to work as expected inside Istio's Service mesh.
This MR adds http name to XP's Services and bumps up a patch version of the chart, similar to how Turing's helm chart has been [updated](https://github.com/caraml-dev/turing/pull/223).
In addition, the [pre-commit](https://pre-commit.com/#intro) tool has been integrated …
=> Satisfy Istio's requirement for named ports  and update pre-commit hooks

.github/workflows/trigger-caraml-doc-sync.yml, README.md
With the migration of `turing-experiments` to the CaraML organisation, we are syncing the docs from `turing-experiments` automatically to https://github.com/caraml-dev/docs. 
This PR introduces an additional workflow which performs this step, which can be found here: https://github.com/caraml-dev/docs/tree/main/.github/actions/trigger-remote-docs-sync
None
=> Add CaraML docs sync workflow

treatment-service/services/experiment_service.go, treatment-service/services/experiment_service_test.go
When multiple experiments are matched by the Fetch Treatment API, the hierarchical experiment filters ensure that ultimately, only one experiment will be selected. However, in a case where there are multiple experiments after `filterByMatchStrength` and there are missing segmenter values to the Fetch Treatment request, the `filterByLookupOrder` function would simply eliminate the experiment(s) from the matches. But, in fact, the overall matches should only be updated if there are non-zero matches for a given segmenter value (which will automatically handle `nil` segmenter values).
This PR addresses the issue above by only updating the filtered experiments if the matches in the current iteration is non-zero, much …
=> Bugfix: Cater to optional segmenter matches in filterByLookupOrder

ui/src/turing/components/configuration/experiments_config/ExperimentsConfigGroup.scss
This PR introduces a tiny fix to the UI to allow the entire route name path of a standard ensembler to be displayed, instead of being truncated.
It involves adding an additional css style property to the existing `experimentSummaryPanel` class to allow text wrapping.
**Before:**
**After:**
=> Addition of text wrapping style to route selection panel 

docs/how-to/06_modifying_experiments.md, ui/src/turing/components/configuration/variables_config/VariablesConfigGroup.js
**What this PR does / why we need it**: This PR adds a small UI bugfix to the remote component meant for Turing router details view, to indicate a `-` where the variable's field has not been set. A small update is also made to the user docs to clarify the experiment versioning behavior.
=> VariablesConfigGroup UI Bugfix / doc update

ui/src/AppRoutes.js, ui/src/Home.js, ui/src/PrivateLayout.js, ui/src/experiments/ExperimentsLandingPage.js, ui/src/experiments/list/ListExperimentsTable.js
**What this PR does / why we need it**: This PR is a follow up from https://github.com/caraml-dev/xp/pull/45 which addresses the navigation regressions introduced by that PR.
Fixes the following issues:
* `ui/src/PrivateLayout.js`, `ui/src/AppRoutes.js` - When the XP app is accessed standalone (primarily during local development), the header bar's project change dropdown was not updating the UI states properly. This is because XP is not a valid first-level MLP app and therefore, `currentApp` would be undefined and cannot be used in `onProjectSelect` as with other apps like Turing. Directly navigating to `/xp` via `onProjectSelect` handler also results in incorrect states because of the underlying implementation of the …
=> Bugfix: Navigation with react-router-dom

api/experiments.yaml, api/schema.yaml, clients/management/managementclient.go, common/api/schema/schema.go, management-service/api/api.go, management-service/controller/experiment_controller.go, management-service/controller/experiment_controller_test.go, management-service/models/experiment.go, management-service/models/experiment_test.go, management-service/pagination/pagination.go, management-service/services/experiment_service.go, management-service/services/experiment_service_test.go, treatment-service/integration-test/fetch_treatment_it_test.go, treatment-service/models/storage_test.go, treatment-service/models/typeconverter.go, treatment-service/models/typeconverter_test.go, treatment-service/testhelper/mockmanagement/api.go, treatment-service/testhelper/mockmanagement/controller/experiment.go, treatment-service/testhelper/mockmanagement/server/server_test.go, treatment-service/testhelper/mockmanagement/service/store.go, ui/src/components/table/BasicTable.js, ui/src/config.js, ui/src/experiments/list/ListExperimentsView.js, ui/src/providers/experiment/context.js, ui/src/turing/components/configuration/experiments_config/ExperimentsConfigGroup.js, ui/src/turing/components/form/standard_ensembler/LinkedRoutesTable.js
This PR introduces a field selector to the `ListExperiments` API of the management service; previously, field selectors only existed for the `ListTreatments` and `ListSegments` APIs. 
The introduction of this field selector would allow more selective control over the fields of the experiment objects to return. Doing so would coincidentally allow the `ListExperimentsTable` of the UI to display larger numbers of experiments (>10) in each page, which it was previously unable to do because querying the API for an entire list of experiments would have resulted in too much data being transferred (due to the unnecessary fields/columns being returned). 
As such, this PR also makes a tiny change to the UI to activate the option to allow users to select the …
=> Add field selector to list experiments API

ui/src/turing/components/configuration/ExperimentEngineConfigDetails.js, ui/src/turing/components/configuration/variables_config/VariablesConfigGroup.js, ui/src/turing/components/form/EditExperimentEngineConfig.js, ui/src/turing/components/form/EditStandardEnsemblerConfig.js, ui/src/turing/components/form/standard_ensembler/LinkedExperimentsContextMenu.js, ui/src/turing/components/form/standard_ensembler/LinkedRoutesTable.js, ui/src/turing/components/form/standard_ensembler/RouteNamePathFlyout.js, ui/src/turing/components/form/standard_ensembler/RouteNamePathRow.js, ui/src/turing/components/form/variables_config/VariableConfigRow.js, ui/src/turing/components/form/variables_config/VariablesConfigPanel.js, ui/src/turing/components/form/variables_config/components/FieldSourceFormLabel.js, ui/src/turing/components/utils/helper.js
UI enhancement to support UPI routers in Turing. Most code changes are due to formatting. 
The only main change is from / `xp/ui/src/turing/components/form/EditExperimentEngineConfig.js` whereby protocol is passed from Turing, all the way to `xp/ui/src/turing/components/form/variables_config/components/FieldSourceFormLabel.js`. 
The value of `Prediction Context` stays the same as payload, as XP only supports HTTP, it is the Turing router that parses the UPI proto and send it to XP. This is mainly for visual aid to be consistency with traffic rules which shows `Prediction Context` too.
If no protocol is passed in, the original `Payload` will be shown.
=> add protocol for prediction_context display

ui/src/experiments/edit/EditExperimentView.js, ui/src/settings/components/form/components/segmenter_section/SegmenterSettings.js, ui/src/turing/components/form/standard_ensembler/RouteNamePathRow.js
**What this PR does / why we need it**: This PR addresses a regression from https://github.com/caraml-dev/xp/pull/45, which caused the Edit experiment view to crash, as we were not retrieving the `projectId` correctly, for passing to the downstream components.
In addition, the following warning related to `EuiButtonIcon` has been fixed:
=> Bugfix: Edit Experiment projectId

ui/src/components/page/LandingView.js
This PR fixes a tiny bug with the UI when a user is led to the landing page with a prompt to create new project settings for a project that has yet to be set up.
Upon clicking on the link in the prompt, the user would not get redirected correctly and nothing happens.
This PR fixes the way in which the `navigate` function from the `react-router-dom` package gets retrieved.
=> Bugfix: Fix retrieval of navigate function

management-service/controller/experiment_controller.go
**What this PR does / why we need it**: This is a minor bugfix for the List Experiments API when 0 records are selected from the DB. We subsequently iterate over the experiments and copy only the required fields (specified by the field selector, if set), to a new array. However, this array was previously uninitialised, leading to `"data": null` as opposed to `"data": []` in the response. (This is implemented correctly for other entities like Segments and Treatments already.)
=> Init empty array for List experiments response

common/utils/typeconverter.go, treatment-service/models/storage.go, treatment-service/models/storage_test.go
This PR introduces some minor refactoring that reduces the memory usage of the Treatment Service by removing the redundancy in storing segmenter values twice in the `ExperimentIndex` struct:
- in the various sets, i.e. `ExperimentIndex.stringSets`, `ExperimentIndex.intSets`, `ExperimentIndex.realSets` 
- in the field `ExperimentIndex.Experiment.Segments`
Given that the Treatment Service only uses the sets of an `ExperimentIndex` to determine a matching experiment, there is no need to store the original copy within `ExperimentIndex.Experiment.Segments`. While this duplication might seem minor and negligible, we have observed instances whereby experiments with a huge number of segmenter values cause a huge increase in memory usage by the Treatment …
=> Reduce treatment service memory usage

plugins/turing/config/config.go, plugins/turing/manager/experiment_manager.go, plugins/turing/manager/experiment_manager_test.go, plugins/turing/runner/experiment_runner.go, plugins/turing/runner/experiment_runner_test.go
After the plugin has been refactored to incorporate the Treatment Service, it has been found that there were a couple of redundant fields that were left hanging in the experiment manager/runner configs that were passed around. This PR simply serves to remove those fields from the said configs:
- `ExperimentManagerConfig.RunnerDefaults` - since the plugin no longer communicates with a central Treatment Service, there is no need for an API endpoint or timeout value
- `ExperimentRunnerConfig.Endpoint` -  same as above
- `ExperimentRunnerConfig.Timeout` - same as above
- `ExperimentRunnerConfig.ProjectID` - this value is a duplicate of the value found in `ExperimentRunnerConfig.TreatmentServiceConfig.ProjectIds`
=> Remove redundant configs from experiment runner

management-service/config/config.go, management-service/config/config_test.go, management-service/database/database.go, management-service/services/configuration_service.go, management-service/testdata/config1.yaml, treatment-service/services/experiment_service.go
This PR is similar to https://github.com/caraml-dev/turing/pull/312 for Turing. It adds a few DB connection configs to avoid intermittent "broken pipe" errors on outgoing connections to the database. This is done by forcefully closing idle connections to the DB through the following configs (all defaults are 0):
```yaml
ConnMaxIdleTime: 0s
ConnMaxLifetime: 0s
MaxIdleConns: 0
MaxOpenConns: 0
```
The values can be overridden at deploy time, if needed, through the [apiConfig](https://github.com/caraml-dev/xp/blob/main/infra/charts/management-service/values.yaml#L58) properties. (No explicit chart changes are needed to support this.)
=> Add DB connection configs

plugins/turing/go.mod, plugins/turing/runner/experiment_runner.go
This PR introduces the asynchronous logging method to the `GetTreatmentForRequest` method of the XP plugin that generates treatments. This functionality was previously left out from an earlier PR as a mistake, and this PR solely serves to fix that.
=> Add logging to plugin fetch treatment method

plugins/turing/runner/experiment_runner.go
There is a bug in the `GetTreatmentForRequest` method of the XP plugin that causes it to return a 400 error when no experiments are matched for the given request. This PR introduces a tiny fix to change the response code to 200 when this happens, just like how this case (no experiments matched) is handled by the standalone Treatment Service (see analogous line [here](https://github.com/caraml-dev/xp/blob/f5eb2bd3c3ce301f392a1120232748a9255ab998/treatment-service/controller/treatment.go#L161))
=> Bugfix: Make experiment runner return a 200 success code when no experiments are matched

.github/workflows/release.yml, .github/workflows/xp.yml, Dockerfile, Makefile, management-service/appcontext/appcontext.go, treatment-service/Dockerfile, treatment-service/Makefile
When updating the helm chart for XP Management Service https://github.com/caraml-dev/helm-charts/pull/220, `Permission Denied` error was faced when trying to run the generated [binary](https://github.com/caraml-dev/helm-charts/actions/runs/4341758906/jobs/7581747169).
Subsequently, we're faced with `Exec format error` which points to our binary file being built on Ubuntu and to be used in an Alpine image. This PR adds multi-stage builds to build our app binaries using an Alpine image and copied over to the latest layer of our Docker image to solve the issue and also make the image leaner.
Fixes #
=> Support multi-stage builds for Management & Treatment Services Dockerfile

plugins/turing/manager/experiment_manager.go
This PR is a follow-up/fix to #67, where the Google client initialisation methods have been updated throughout the XP repo. Unfortunately, the experiment manager in the XP plugin has been left out of the previous PR and needs to be updated too.
This PR makes the aforementioned update.
Fixes #
=> Bugfix: Update experiment engine Google client initialisation

management-service/database/database.go
Similar to https://github.com/caraml-dev/turing/pull/331, the Gorm library has been updated to v2 in https://github.com/caraml-dev/xp/pull/43. As there was a bug discovered in how we were using the Gorm methods to save to the DB whereby nested fields do not get updated in their respective tables, we're now updating the Gorm configs in the XP repository too to ensure that this bug does not occur again (even though we are currently not saving nested fields in the DB in XP).
Fixes #
=> Add gorm config to update nested fields

management-service/database/database.go
This PR reverts the changes introduced in #71, as there is no need to enforce all associations of a Gorm object to be saved. A similar change was first introduced in https://github.com/caraml-dev/turing/pull/331 but it has since been removed in favour of a more precise manner of updating tables that contain nested fields of a Gorm object.
Fixes #
=> Revert PR (#70) - addition of gorm config to update nested fields in the db

README.md, common/config/config.go, common/config/config_test.go, tests/e2e/fixtures/services.py, treatment-service/integration-test/fetch_treatment_it_test.go
* This PR replaces the `::` delimiter with `_` so `DBCONFIG::PASSWORD` becomes `DBCONFIG_PASSWORD`
* This is to allow the setting of environment variables in `env` field in K8s PodSpec, which opens up the option to set env vars using ConfigMaps or Secrets
* Currently caraml-dev/helm-charts https://github.com/caraml-dev/helm-charts/actions/runs/4943497133/jobs/8838050166?pr=243 is failing because of the use of this delimiter
<!--
*Automatically closes linked issue when PR is merged.
Usage: `Fixes #<issue number>`, or `Fixes (paste link of issue)`.
nil
cc @mbruner
=> Set env config to use _ delimiter instead of ::

management-service/go.mod, management-service/go.sum, plugins/turing/go.mod, plugins/turing/go.sum, treatment-service/go.mod, treatment-service/go.sum
This PR updates the version of MLP uses in order to incorporate this change [here](https://github.com/caraml-dev/mlp/pull/84), which allows XP to use workload identity-enabled service account to authenticate all its outgoing resources.
Fixes #
=> Update mlp dependency

ui/package.json, ui/src/experiments/components/form/validation/schema.js, ui/src/experiments/list/search/SearchExperimentsPanel.js, ui/src/experiments/list/search/SearchExperimentsPanel.scss, ui/src/experiments/list/search/validation/schema.js, ui/src/segments/components/form/validation/schema.js, ui/src/settings/segmenters/components/form/validation/schema.js, ui/yarn.lock
Similar to https://github.com/caraml-dev/turing/pull/387, this PR to fixes broken validation schemas caused by the upgrade of the `yup` package in PR #591 - these changes can largely be grouped into the following:
- When using the same `Schema.when` function but passing a function directly as an argument instead of the builder object, the signature of the expected function has also been updated from `(value, schema)=> Schema): Schema` to `(values: any[], schema) => Schema): Schema`.
Existing schemas that do not follow this convention now have been updated to reflect the new expected array:
Example:
```javascript
// before
some_field: yup.string().when("some_other_field", (some_other_field, schema) =>
some_other_field ? yup.string().required("this is …
```
=> fix(ui): Fix yup validation bug

plugins/turing/manager/experiment_manager.go
In https://github.com/caraml-dev/turing/pull/390, the `yup-ast` package has been updated to use a much newer and updated alternative. However, after fixing that problem, it was found that the existing experiment engine `yup-ast` schema specified in [XP](https://github.com/caraml-dev/xp/blob/cb06edaaf409077b5abf7fed0b803984b6decf7e/plugins/turing/manager/experiment_manager.go#L38C1-L38C36) isn't working, i.e. the validation schema is invalid and `yup` allows the entire config to pass even if it fails certain fields in the validation schema.
Apparently what's needed to be fix is to simply add additional square brackets when defining a list of validation checks in the schema specified for a specific field (only when using the `yup.shape` check). I've …
=> fix(ui): Update broken yup-ast schema

ui/src/settings/components/form/validation/schema.js
This PR introduces an additional fix to the yup validation schema, as a follow up from #80. In particular, the fix in this PR addresses this change:
- When using the same `Schema.when` function but passing a function directly as an argument instead of the builder object, the signature of the expected function has also been updated from `(value, schema)=> Schema): Schema` to `(values: any[], schema) => Schema): Schema`.
Existing schemas that do not follow this convention now have been updated to reflect the new expected array:
Example:
```javascript
// before
some_field: yup.string().when("some_other_field", (some_other_field, schema) =>
some_other_field ? yup.string().required("this is needed") : schema
),
// after
some_field: …
```
=> fix(ui): Fix segmenter yup validation schema

Dockerfile, plugins/turing/Dockerfile, treatment-service/Dockerfile
With the upgrade of Go from 1.18 to 1.21 in all of XP's components, we need to update the docker base image used to build them. This PR updates the version of Go in these base images from 1.18 to 1.21.
Fixes #
=> chore(docker): Update base docker images

ui/src/settings/segmenters/components/form/validation/schema.js
It seems like after updating yup/elastic UI packages, array values in the `EuiTextArea` are expressed as a JSON literal, e.g. `"[\"new\"]"` and these values no longer get automatically parsed into a JSON array at the yup validation stage. As a result, all the `.array()` validations that were performed no longer work and fail (because they report a string being present instead). The screenshot attached shows how the validation reports an error even though nothing is wrong with the input in the text fields.
An additional step is thus introduced to manually parse the literal input into a JSON array (failing the validation check if it isn't), and to validate the parsed array with respect to the original schema. 
Fixes #
=> fix(ui): Add helper function to cast string to array before yup validation

treatment-service/models/storage.go
**What this PR does / why we need it**: 
When pubsub disabled and poll enabled, every time poller runs XP treatment service tries to acquire write lock and the treatment service refreshes the local storage by doing multiple calls to management service and update the data/maps.
This causes other part that use RLock to be blocked until all the calls and update are done. 
This MR moved the write lock to after all the calls are completed, this reduces duration of RLock being blocked
=> feat: improve locking: lock only after fetch completed

plugins/turing/manager/experiment_manager.go, treatment-service/appcontext/appcontext.go, treatment-service/appcontext/appcontext_test.go, treatment-service/integration-test/fetch_treatment_it_test.go, treatment-service/models/storage.go
In the XP plugin manager, the Management Service client is always initialised with a Google client, meaning that it always expects a Google service account's or user's credentials to always be present for authenticating all outgoing requests from the plugin. Failing to configure either of these will cause the plugin manager to fail at start up since the Google client cannot be initialised properly. This PR removes the need of any Google credentials and instead allows the Management Service client to be started up with a default HTTP client.
In a somewhat similar fashion, the XP Treatment Service also attempts to initialise a Google client with the aforementioned credentials (and fails at start up if they aren't configured) if the …
=> fix(xp-treatment,plugin): Fix treatment service and plugin's method of initiating management service client

common/testutils/pubsub.go, treatment-service/services/messagequeue/pubsub_message_queue_service.go, treatment-service/testhelper/mockmanagement/server/server_test.go
Message ordering is not turned on for PubSub subscriptions created by the Treatment Service (and by extension the XP plugin), which means that messages received are not guaranteed to be in order. This poses a problem when there is a high volume of messages sent by the Management Service in a short span of time, as the order of messages received is important since these messages directly impact how the correct treatment is assigned to each request (e.g. an experiment is repeatedly turned on and off over a short period of time). 
This PR thus turns on message ordering all subscriptions created to ensure that all instances of the Treatment Service/plugin   are consistent in serving the same treatment to each request by maintaining strict message …
=> fix(treatment-service): Add pubsub message ordering flag
